export default function financeiroPatch(){
  return {
    name:'zoe-financeiro-conciliacao-parcial',
    enforce:'pre',
    transform(code,id){
      if(!id.endsWith('/FinanceiroPlus.jsx')&&!id.endsWith('FinanceiroPlus.jsx')) return null;
      let out=code;

      const blocoFuncoes=/ const mesImp=imp\?\.meses\?\.\[imp\.indice\],pend=mesImp\?\.itens\?\.filter\(t=>t\.revisar&&!t\.duplicado\)\|\|\[\];[\s\S]*? const concluirImportacao=/;
      const novoBloco=` const mesImp=imp?.meses?.[imp.indice],pend=mesImp?.itens?.filter(t=>t.revisar&&!t.duplicado)||[],prontos=mesImp?.itens?.filter(t=>!t.revisar&&!t.duplicado)||[];
 const gravarLancamentos=(itens,mesAlvo,parcial=false)=>{const novas=(itens||[]).map(corrigirLegado);atualiza(f=>{const existentes=new Set((f.transacoes||[]).map(chave)),realmenteNovas=novas.filter(t=>{const k=chave(t);if(existentes.has(k))return false;existentes.add(k);return true});return{...f,transacoes:[...(f.transacoes||[]),...realmenteNovas],documentos:[...(f.documentos||[]),{id:uid('doc'),nome:imp?.arquivo||'Importação',mes:mesAlvo,itens:realmenteNovas.length,data:hoje(),parcial}],importacoesConciliadas:[...(f.importacoesConciliadas||[]),{arquivo:imp?.arquivo||'Importação',mes:mesAlvo,itens:realmenteNovas.length,data:hoje(),parcial}],importacaoPendente:null}})};
 const montarFilaAposRemocao=(base,indice,itensRestantes,etapaPreferida='conciliacao')=>{let meses=(base?.meses||[]).map((m,i)=>i===indice?{...m,itens:itensRestantes,status:'aguardando'}:m);if(!itensRestantes.length)meses=meses.filter((_,i)=>i!==indice);if(!meses.length)return{...base,meses:[],indice:0,etapa:'finalizado'};const novoIndice=Math.min(indice,meses.length-1);return{...base,meses,indice:novoIndice,etapa:itensRestantes.length?etapaPreferida:'meses'}};
 const enviarItemResolvido=id=>{const atual=importacaoMemoria||imp;if(!atual)return;let mi=-1,item=null;(atual.meses||[]).some((m,i)=>{const achou=(m.itens||[]).find(t=>t.id===id);if(achou){mi=i;item=achou;return true}return false});if(!item||item.revisar||item.duplicado)return;gravarLancamentos([item],atual.meses[mi].mes,true);const restantes=(atual.meses[mi].itens||[]).filter(t=>t.id!==id&&t.revisar&&!t.duplicado);const next=montarFilaAposRemocao(atual,mi,restantes,restantes.length?'conciliacao':'meses');importacaoMemoria=next;setImp(next);salvarConciliacaoPendente(next).catch(()=>{});setMesRef(atual.meses[mi].mes)};
 const resolver=(id,categoria)=>{let deveEnviar=false;persistImp(o=>({...o,meses:o.meses.map((m,i)=>i!==o.indice?m:{...m,itens:m.itens.map(t=>{if(t.id!==id)return t;const z=regras({...t,categoria,confianca:'CONFIRMADO_MANUAL'}),final={...z,revisar:Boolean(z.possivelDuplicado)||Boolean(z.possivelPagamentoFatura)||z.categoria==='Outros'};deveEnviar=!final.revisar&&!final.duplicado;return final})})}));if(deveEnviar)setTimeout(()=>enviarItemResolvido(id),0)};
 const resolverDuplicado=(id,acao)=>{if(acao==='ignorar'){const atual=importacaoMemoria||imp;if(!atual)return;const m=atual.meses?.[atual.indice];if(!m)return;const restantes=(m.itens||[]).filter(t=>t.id!==id);const next=montarFilaAposRemocao(atual,atual.indice,restantes.filter(t=>t.revisar&&!t.duplicado),restantes.length?'conciliacao':'meses');importacaoMemoria=next;setImp(next);salvarConciliacaoPendente(next).catch(()=>{});return}let deveEnviar=false;persistImp(o=>({...o,meses:o.meses.map((m,i)=>i!==o.indice?m:{...m,itens:m.itens.map(t=>{if(t.id!==id)return t;const z=regras({...t,duplicado:false,possivelDuplicado:false,duplicadoStatus:'kept',confianca:t.categoria==='Outros'?'A_REVISAR':'CONFIRMADO_MANUAL'}),final={...z,revisar:z.categoria==='Outros'||Boolean(z.possivelPagamentoFatura)};deveEnviar=!final.revisar;return final})})}));if(deveEnviar)setTimeout(()=>enviarItemResolvido(id),0)};
 const resolverPagamentoFatura=(id,acao)=>{let deveEnviar=false;persistImp(o=>({...o,meses:o.meses.map((m,i)=>i!==o.indice?m:{...m,itens:m.itens.map(t=>{if(t.id!==id)return t;if(acao==='fatura'){const z={...t,natureza:'PAGAMENTO_FATURA',categoria:'Pagamento de fatura',impactoReceita:0,impactoDespesa:0,ignorarResumo:true,pagamentoFatura:true,possivelPagamentoFatura:false,confianca:'CONFIRMADO_MANUAL',revisar:false};deveEnviar=true;return z}const z=regras({...t,possivelPagamentoFatura:false,confianca:t.categoria==='Outros'?'A_REVISAR':'CONFIRMADO_MANUAL'});return{...z,revisar:z.categoria==='Outros'||Boolean(z.possivelDuplicado)}})})}));if(deveEnviar)setTimeout(()=>enviarItemResolvido(id),0)};
 const enviarProntos=()=>{if(!mesImp||confirmando)return;const enviar=(mesImp.itens||[]).filter(t=>!t.revisar&&!t.duplicado);if(!enviar.length)return aviso(pend.length?\`Ainda faltam \${pend.length} pendência(s) neste mês.\`:'Não há lançamentos prontos para enviar.');setConfirmando(true);try{gravarLancamentos(enviar,mesImp.mes,pend.length>0);const restantes=(mesImp.itens||[]).filter(t=>t.revisar&&!t.duplicado);const next=montarFilaAposRemocao(imp,imp.indice,restantes,restantes.length?'conciliacao':'meses');importacaoMemoria=next;setImp(next);salvarConciliacaoPendente(next).catch(()=>{});setMesRef(mesImp.mes);if(restantes.length){setTela('importacao');aviso(\`\${enviar.length} lançamento(s) enviados. Ficou só \${restantes.length} pendência(s) em \${mesLabel(mesImp.mes)}.\`)}else{setTela(next.etapa==='finalizado'?'importacao':'resumo');aviso(\`\${mesLabel(mesImp.mes)} enviado e retirado da fila de conciliação.\`)}}catch(e){aviso(e.message||'Não consegui enviar os lançamentos conciliados.')}finally{setConfirmando(false)}};
 const confirmarMes=enviarProntos;
 const concluirImportacao=`;
      if(!blocoFuncoes.test(out)) throw new Error('Patch financeiro: bloco de conciliação não encontrado');
      out=out.replace(blocoFuncoes,novoBloco);

      const marcadorPreparar=' async function preparar(file)';
      if(!out.includes(marcadorPreparar)) throw new Error('Patch financeiro: preparar não encontrado');
      const reconciliador=` const instituicaoFatura=t=>{const s=norm(\`\${t?.conta||''} \${t?.descricao||''} \${t?.origemDocumento||''}\`);const r=[['c6',/c6 bank|c6bank|\\bc6\\b/],['nubank',/nubank|nu pagamentos/],['inter',/banco inter|inter bank|\\binter\\b/],['itau',/itau/],['bradesco',/bradesco/],['santander',/santander/],['caixa',/caixa economica|\\bcaixa\\b/],['bb',/banco do brasil|\\bbb\\b/],['mercadopago',/mercado pago|mercadopago/],['picpay',/picpay/]];return r.find(([,rx])=>rx.test(s))?.[0]||''};
 const pareceCompraFatura=t=>t?.natureza==='COMPRA_CARTAO'||/fatura|cartao|credito/.test(norm(\`\${t?.origemDocumento||''} \${t?.conta||''}\`));
 const parecePagamento=t=>t?.tipo==='saida'&&!t?.ignorarResumo&&!pareceCompraFatura(t)&&/pagamento|fatura|cartao|transferencia|transfer|pix/.test(norm(\`\${t?.descricao||''} \${t?.natureza||''}\`));
 const diasDiff=(a,b)=>{const x=new Date(\`\${a}T12:00:00\`),y=new Date(\`\${b}T12:00:00\`);return Number.isFinite(x-y)?Math.abs(x-y)/86400000:999};
 const crossReconcileFatura=(novos,existentes)=>{const todos=[...(existentes||[]),...(novos||[])],compras=todos.filter(pareceCompraFatura),pagamentos=todos.filter(parecePagamento),ajustesExistentes=[];const porInstMes=new Map();compras.forEach(c=>{const inst=instituicaoFatura(c);if(!inst)return;const k=\`\${inst}|\${c.competenciaAnalitica||mes(c.data)}\`;const g=porInstMes.get(k)||{itens:[],total:0,inst,competencia:c.competenciaAnalitica||mes(c.data)};g.itens.push(c);g.total+=Number(c.impactoDespesa??c.valor??0);porInstMes.set(k,g)});const avaliar=p=>{const inst=instituicaoFatura(p);if(!inst)return p;const comps=[...porInstMes.values()].filter(g=>g.inst===inst).map(g=>{const diff=Math.abs(Number(p.valor||0)-g.total),tol=Math.max(5,g.total*.02),datas=g.itens.map(x=>x.data).filter(Boolean),maisRecente=datas.sort().at(-1),dias=maisRecente?diasDiff(p.data,maisRecente):999;return{g,diff,tol,dias}}).filter(x=>x.dias<=45).sort((a,b)=>(a.diff/a.tol)-(b.diff/b.tol));if(!comps.length)return p;const best=comps[0];if(best.diff<=best.tol){return{...p,natureza:'PAGAMENTO_FATURA',categoria:'Pagamento de fatura',impactoReceita:0,impactoDespesa:0,ignorarResumo:true,pagamentoFatura:true,faturaVinculada:{instituicao:inst,competencia:best.g.competencia,valor:best.g.total},possivelPagamentoFatura:false,revisar:false,confianca:'CONFIRMADO_AUTO'}}if(best.diff<=Math.max(20,best.g.total*.08)){return{...p,possivelPagamentoFatura:true,faturaVinculada:{instituicao:inst,competencia:best.g.competencia,valor:best.g.total},revisar:true,confianca:'A_REVISAR'}}return p};const novosOut=(novos||[]).map(avaliar);(existentes||[]).forEach(e=>{if(!parecePagamento(e))return;const z=avaliar(e);if(z.natureza==='PAGAMENTO_FATURA'&&e.natureza!=='PAGAMENTO_FATURA')ajustesExistentes.push(z)});return{itens:novosOut,ajustesExistentes}};
`;
      out=out.replace(marcadorPreparar,reconciliador+marcadorPreparar);

      const trechoDedupe='itens=applyDuplicateDetection(itens,ts).map(t=>regras(t));const meses=agrupa(itens);';
      if(!out.includes(trechoDedupe)) throw new Error('Patch financeiro: dedupe não encontrado');
      out=out.replace(trechoDedupe,`itens=applyDuplicateDetection(itens,ts).map(t=>regras(t));const cruz=crossReconcileFatura(itens,ts);itens=cruz.itens;if(cruz.ajustesExistentes.length)atualiza(f=>({...f,transacoes:(f.transacoes||[]).map(t=>cruz.ajustesExistentes.find(a=>chave(a)===chave(t))||t)}));const meses=agrupa(itens);`);

      const listaAntiga='mesImp.itens.filter(t=>!t.duplicado).slice(0,120).map';
      if(!out.includes(listaAntiga)) throw new Error('Patch financeiro: lista de itens não encontrada');
      out=out.replace(listaAntiga,'pend.slice(0,120).map');

      const chipDuplicado="{t.possivelDuplicado&&chip('POSSÍVEL DUPLICIDADE','#FFEDD5','#9A3412')}";
      if(!out.includes(chipDuplicado)) throw new Error('Patch financeiro: chip duplicidade não encontrado');
      out=out.replace(chipDuplicado,`${chipDuplicado}{t.possivelPagamentoFatura&&chip('POSSÍVEL PAGAMENTO DE FATURA','#E0F2FE','#075985')}`);

      const blocoPossivel="{t.possivelDuplicado&&<div style={{marginTop:9,padding:10,borderRadius:12,background:'#FFF'}}><b style={{fontSize:12,color:'#9A3412'}}>A ZOE encontrou um lançamento muito parecido</b>{t.duplicadoMatch&&<div style={{fontSize:11,color:C.ink2,marginTop:5}}>{fmtData(t.duplicadoMatch.data)} • {t.duplicadoMatch.descricao} • {formatoMoeda(t.duplicadoMatch.valor)}</div>}<div style={{display:'grid',gridTemplateColumns:'1fr 1fr',gap:8,marginTop:9}}><button onClick={()=>resolverDuplicado(t.id,'ignorar')} style={{border:'1px solid #FED7AA',background:'#FFF7ED',color:'#9A3412',borderRadius:10,padding:'9px 8px',fontWeight:700}}>É duplicado • ignorar</button><button onClick={()=>resolverDuplicado(t.id,'manter')} style={{border:'1px solid #C7D2FE',background:'#EEF2FF',color:'#4338CA',borderRadius:10,padding:'9px 8px',fontWeight:700}}>Não é • manter</button></div></div>}";
      if(!out.includes(blocoPossivel)) throw new Error('Patch financeiro: bloco possível duplicidade não encontrado');
      out=out.replace(blocoPossivel,`${blocoPossivel}{t.possivelPagamentoFatura&&<div style={{marginTop:9,padding:10,borderRadius:12,background:'#EFF8FF',border:'1px solid #BAE6FD'}}><b style={{fontSize:12,color:'#075985'}}>Pode ser pagamento da fatura {String(t.faturaVinculada?.instituicao||'').toUpperCase()}</b><div style={{fontSize:11,color:C.ink2,marginTop:5}}>Pagamento: {formatoMoeda(t.valor)} • compras vinculadas: {formatoMoeda(t.faturaVinculada?.valor||0)} • competência {mesLabel(t.faturaVinculada?.competencia)}</div><div style={{display:'grid',gridTemplateColumns:'1fr 1fr',gap:8,marginTop:9}}><button onClick={()=>resolverPagamentoFatura(t.id,'fatura')} style={{border:'1px solid #7DD3FC',background:'#E0F2FE',color:'#075985',borderRadius:10,padding:'9px 8px',fontWeight:700}}>Sim • pagamento de fatura</button><button onClick={()=>resolverPagamentoFatura(t.id,'normal')} style={{border:'1px solid #D1D5DB',background:'#fff',color:C.ink2,borderRadius:10,padding:'9px 8px',fontWeight:700}}>Não • manter normal</button></div></div>}`);

      const botaoRegex=/<Btn onClick=\{confirmarMes\} disabled=\{pend\.length>0\|\|confirmando\} style=\{\{width:'100%',marginTop:12\}\}>\{confirmando\?'Confirmando\.\.\.':`Finalizar e lançar em \$\{mesLabel\(mesImp\.mes\)\}`\}<\/Btn>/;
      if(!botaoRegex.test(out)) throw new Error('Patch financeiro: botão final não encontrado');
      out=out.replace(botaoRegex,`<Card style={{marginTop:12,background:'#F7F3FF'}}><div style={{fontSize:12,color:C.ink2}}><b>{prontos.length}</b> lançamento(s) já conciliado(s) podem ser enviados agora.</div>{pend.length>0&&<div style={{fontSize:11,color:'#92400E',marginTop:4}}>As {pend.length} pendência(s) ficam guardadas e serão as únicas exibidas quando você voltar para este mês.</div>}</Card><Btn onClick={enviarProntos} disabled={prontos.length===0||confirmando} style={{width:'100%',marginTop:10}}>{confirmando?'Enviando...':pend.length>0?\`Enviar \${prontos.length} conciliado(s) e deixar \${pend.length} pendente(s)\`:\`Finalizar e lançar em \${mesLabel(mesImp.mes)}\`}</Btn>`);

      return {code:out,map:null};
    }
  };
}
